---

- name: "configuration play." 
  hosts: configure_server
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udacity-circle.cay0m4kje9c1.eu-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: c5jaDcZN3W6Epr78
    TYPEORM_DATABASE: postgres
    ANSIBLE_HOST_KEY_CHECKING: false

  pre_tasks:
    # - name: "wait 600 seconds for target connection to become reachable/usable."
    #   wait_for:
    #     timeout: 300

    # - name: "install python for Ansible."
    # - name: "Update/upgrade packages"
    #   command: sudo apt-get update
    - name: "install node"
      command: sudo apt-get install -y nodejs
    - name: Install npm
      command: sudo apt-get install -y npm
    - name: "Install pm2"
      command: sudo npm install pm2 -g
    - name: "Install git"
      command: sudo apt-get install -y git
    - name: Git clone
      command: git clone https://github.com/nishantk12/circle_ci_learning.git 
      args:
        creates: ./circle_ci_learning
    - name: start the backend server
      command: pm2 start npm -- start
      args:
        chdir: circle_ci_learning/backend/
      

  roles:
    - configure_server