---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: database-1.ckkn0xi9uixf.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: postgres
    TYPEORM_DATABASE: postgres

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for:
        timeout: 300

    # - name: "install python for Ansible."
    - name: "Update/upgrade packages"
      command: sudo apt-get update
    - name: "install node"
      command: sudo apt install nodejs
    - name: "Install pm2"
      command: npm install pm2 -g
    - name: "Install git"
      command: sudo apt-get install -y git
    - name: get the node to work on port 80
      command: sudo apt-get install libcap2-bin; sudo setcap cap_net_bind_service=+ep /usr/local/bin/node
    - name: Git clone
      command: git clone git@github.com:nishantk12/circle_ci_learning.git
    - name: start the backend server
      command: cd circle_ci_learning/backend/; pm2 start npm -- start;
      

  roles:
    - configure-server